### ISSUE TITLE
Camera plugin changes dark colors to the background tiles 

### ISSUE THREAD

**Issue by Declanh5** [JannisX11/blockbench-plugins#479] opened 2024-02-21 13:00 UTC
Any elements in my animation that are black are fine while not using the camera, but as soon as I make a GIF using the animation, the black is converted to the background.

How do I fix this?

**Comment by JannisX11** [comment] 2024-03-16 17:31
Duplicate of https://github.com/JannisX11/blockbench/issues/2076

**Closed by JannisX11** 2024-03-16 17:31 UTC
