### ISSUE TITLE
[GeckoLib Animation Utils animating is broken]

### ISSUE THREAD

**Issue by BubbaGump77** [JannisX11/blockbench-plugins#549] opened 2024-05-31 16:02 UTC
rotation points don't show up when i click on a bone and it doesn't display CTRL+Y changes or any other changes. This is really annoying, please fix.

**Comment by ShadowLink2016** [comment] 2024-06-01 05:48
Having the same issue currently as well. The error log also gives an error every time me and my mod team click on bones on our models while attempting to animate them. 

![image_2024-06-01_014803637](https://github.com/JannisX11/blockbench-plugins/assets/21695110/0fd2f4bf-0c8d-4584-bccc-a4a8cd94ce6b)

**Comment by JannisX11** [comment] 2024-06-01 13:43
Duplicate of #548

**Closed by JannisX11** 2024-06-01 13:43 UTC
