### ISSUE TITLE
[Mine-imator Model Exporter]

### ISSUE THREAD

**Issue by Jihadz1** [JannisX11/blockbench-plugins#617] opened 2024-09-16 18:39 UTC
Hi! My name is Jihad and im from Indonesian. (Sorry for my language is bad)

I just wanna say about this plugin is not working properly. I am exporting my model results to Mineimator and the results are terrible. Here are some pictures as proof of this.

![Gambar WhatsApp 2024-09-17 pukul 01 36 37_617a4f59](https://github.com/user-attachments/assets/d048e0af-93bd-4116-9043-07db48f46573)
![Gambar WhatsApp 2024-09-17 pukul 01 35 28_6c1a6291](https://github.com/user-attachments/assets/3fc4e1aa-16ba-4067-8d0b-787b68e791c6)
![Gambar WhatsApp 2024-09-17 pukul 01 35 08_c5b5cd8f](https://github.com/user-attachments/assets/83ce19ea-aa4b-4d3b-bb4e-fa548d6e4797)

I have followed the instructions, but the result is still the same. Pliiss I just want my waifu to be real!!!

**Comment by JannisX11** [comment] 2024-11-03 17:53
Duplicate of #564

**Closed by JannisX11** 2024-11-03 17:53 UTC
Labels: bug report
