### ISSUE TITLE
[Mod Utils] VoxelShapes exporter doesn't work with rotated cubes

### ISSUE THREAD

**Issue by grillo78** [JannisX11/blockbench-plugins#156] opened 2021-05-28 12:28 UTC
I tried to export the corner and this was the result....
![image](https://user-images.githubusercontent.com/19859573/119983741-dac67f80-bfc0-11eb-8654-6f662e637248.png)

**Comment by JTK222** [comment] 2021-05-28 12:36
It doesn't work, because Minecraft doesn't allow VoxelShapes to be rotated.
Until this changes the plugin won't support it either.

Jannis, you can close this as it's not a bug, but intended behavior.

**Closed** 2022-02-23 15:35 UTC
