### ISSUE TITLE
Mod Utils [Issue] Newer .tbl files not importing correctly

### ISSUE THREAD

**Issue by CammiePone** [JannisX11/blockbench-plugins#88] opened 2020-08-10 05:32 UTC
So I attempted to import a .tbl file made in 1.15 Tabula into Blockbench using Mod Utils, and it just didn't import anything except the root bone (which I'm not even sure was in the original .tbl file as I'm attempting to do this for a friend) @JTK222. I'm not sure if this happens on older versions of Blockbench, or with older .tbl files, but I'm wagering that this is an issue with newer versions of .tbl files.
![image](https://user-images.githubusercontent.com/16853086/89754179-dd46ff80-daa8-11ea-8e20-937e0faa9be9.png)
![image](https://user-images.githubusercontent.com/16853086/89754295-59414780-daa9-11ea-8528-5d3816944579.png)

**Comment by JTK222** [comment] 2020-08-10 06:08
Duplicate of #83, the tabula model file format changed with the 1.15 tabula version

**Closed** 2020-08-10 06:10 UTC
