### ISSUE TITLE
[MTools] Bridge Edge Loops is not working.

### ISSUE THREAD

**Issue by silentpoets** [JannisX11/blockbench-plugins#622] opened 2024-09-27 04:25 UTC
as title states, i select the faces of two separate meshes to connect them via bridge edge loops, but nothing happens. they just become two holes. i would really like for this to be fixed ASAP as i really really need this for what im working on.

**Comment by JannisX11** [comment] 2024-10-03 20:26
Duplicate of #538

**Closed by JannisX11** 2024-10-03 20:26 UTC
